### ISSUE TITLE
【プログラマのためのDocker教科書 第2版】5.3 Dockerfileビルドエラーについて

### ISSUE THREAD

**Issue by oshiro-pooh** [asashiho/dockertext2#2]
@asashiho 
阿佐様

お世話になっております。
【プログラマのためのDocker教科書 第2版】の読者です。
日頃、上記書籍を使ってDockerの勉強をさせていただいております。
(最近業務でもDockerを使用するようになってのですが、イメージやコンテナ周りの理解が追いついておらず、非常に助けられました。)

上記書籍の5.3でのDockerfileビルドに関して以下のエラーが発生しました。

```
ooshirotoshisukenoMacBook-Air:multi-stage oshiro-pooh$ docker build -t greet .
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM golang:1.8.4-jessie AS builder
1.8.4-jessie: Pulling from library/golang
85b1f47fba49: Pull complete 
5409e9a7fa9e: Pull complete 
661393707836: Pull complete 
9d718ab8b1b0: Pull complete 
cdfb169b668c: Pull complete 
0f4bf831cc47: Pull complete 
2e82858ddeb5: Pull complete 
Digest: sha256:e8ff3ea3c2666f85c2f7576914a3c15b9f71f7ab92507882b71f1b5a2c49c203
Status: Downloaded newer image for golang:1.8.4-jessie
 ---> c43e4acbfaba
Step 2/9 : WORKDIR /go/src/github.com/asashiho/dockertext-greet
 ---> Running in ff0f53257bfe
Removing intermediate container ff0f53257bfe
 ---> fb76c5721518
Step 3/9 : RUN go get -d -v github.com/urfave/cli
 ---> Running in 683e874f9ef0
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
package github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
	/usr/local/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
	/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
The command '/bin/sh -c go get -d -v github.com/urfave/cli' returned a non-zero code: 1
```

おそらく、Goのバージョンと実行コマンドの兼ね合いの不備だと思うのですが、回避策をご教示頂く事は可能でしょうか？？
ちなみに、サンプルコードは以下の最新のmaserブランチものもをクローン済みです。
https://github.com/asashiho/dockertext2/

お忙しい中恐縮ですが、何卒よろしくお願い致します。

---

**Comment by YukiHiyori** [comment]
@asashiho
阿佐様

私も`oshiro-pooh`様と全く同様の事象が発生しています。
簡単に調べたところ、過去に似たような事象が複数報告されておりましたが、特に回避策が乗ってるわけでもなく困っております。
時期的に、9月以降のバージョンでトラブルがあったようです。
https://github.com/containerd/containerd/issues/3646

回避策等あればご教授いただければ幸いです。

**Comment by asashiho** [comment]
ご質問いただきありがとうございます&&ご連絡遅くなり申し訳ありません。

Goのベースイメージのバージョンアップ(->1.13)とコードを一部修正しましたので、大変お手数ですが再度ご確認いただけると大変ありがたいです！

**Comment by soana-0702** [comment]
@asashiho さま
ご対応いただきありがとうございます！

先程最新のソースをクローンしdocker build したところ、無事完了し、そのあとのコマンドも動作することを確認できました。これで学習を再開できます。ありがとうございます 😃

**Comment by YukiHiyori** [comment]
@asashiho さま
ご対応いただきありがとうございます！

先程最新のソースをクローンしdocker build したところ、無事完了し、そのあとのコマンドも動作することを確認できました。これで学習を再開できます。ありがとうございます 😃

**Comment by oshiro-pooh** [comment]
@asashiho
阿佐様

>Goのベースイメージのバージョンアップ(->1.13)とコードを一部修正しましたので、大変お手数ですが再度ご確認いただけると大変ありがたいです！

ご多忙の折、修正頂きありがとうございました。(確認が遅くなり誠に申し訳ありません。)
私の端末でも無事動作しました。
引き続き、学習を進めさせて頂きます。
